version: '3.1'

services:
  db:
    image: postgres:12.3
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: 'munity'
      POSTGRES_PASSWORD: 'munity'
      POSTGRES_DB: 'model_unity'